backend/admin_extension/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from . import views

# fmt: off
urlpatterns = [
  path('dump/', views.dump, name='dump'),
  path('clear_cache/', views.clear_cache, name='clear_cache'),
]

backend/core/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

# fmt: off
urlpatterns = [
    path(f"{settings.ADMIN_PATH}ext/", include(("admin_extension.urls", "adminext"), namespace="adminext")),
    path(settings.ADMIN_PATH, admin.site.urls),

    path(f"{settings.API_PATH}position/",   include(("positions.urls", "position"),   namespace="position")),
    path(f"{settings.API_PATH}people/",     include(("people.urls",    "people"),     namespace="people")),
    path(f"{settings.API_PATH}universe/",   include(("universe.urls",  "universe"),   namespace="universe")),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# fmt: on

backend/admin_extension/views.py
# -*- coding: utf-8 -*-
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.core.cache import cache

from core.services.dump import dump_data


@login_required
def dump(request):
    dump_data()
    return JsonResponse({"dump_data": "ok"})


@login_required
def clear_cache(request):
    cache.clear()
    return JsonResponse({"clear_cache": "ok"})

backend/admin_extension/templates/index.html
{% extends 'admin/index.html' %}

{% block extrahead %}
<style>
.ext {
  background: var(--darkened-bg);
  padding: 15px;
  margin-bottom: 20px;
}
.ext h2 {
  background: none;
  margin-bottom: 16px;
  font-size: 1.125rem;
  color: var(--body-fg);
  font-weight: 400;
  margin-top: 0;
}
.ext button {
  background: var(--button-bg);
  padding: 10px 15px;
  border: none;
  border-radius: 4px;
  color: var(--button-fg);
  cursor: pointer;
  transition: background 0.15s;
}
.ext button:hover {
  background: var(--button-hover-bg);
}
</style>
{% endblock %}

{% block content %}

<div class="ext">
  <div class="ext__buttons">
    <button id="dump" type="button">Dump data</button>
    <button id="cache" type="button">Clear cache</button>
  </div>
</div>

<div id="content-main">
  {% include "admin/app_list.html" with app_list=app_list show_changelinks=True %}
</div>

<script>
document.getElementById("dump").addEventListener('click', () => {
  const url = "{% url 'adminext:dump' %}";
  const httpRequest = new XMLHttpRequest();
  httpRequest.open("GET", url, true);
  httpRequest.send();
  alert("Data dump initialized. Please wait until the process is done.")
})

const dumpBtn = document.getElementById("dump");

document.getElementById("cache").addEventListener('click', () => {
  const url = "{% url 'adminext:clear_cache' %}";
  const httpRequest = new XMLHttpRequest();
  httpRequest.open("GET", url, true);
  httpRequest.send();
  alert("Cache cleared.")
})
</script>

{% endblock %}